---
swagger: '2.0'
info:
  version: '1.0'
  title: API for pusing data to hjernen
basePath: "/"
paths:
  "/set_pi_ip":
    post:
      operationId: postPiIp
      x-mojo-name: post_pi_ip
      x-mojo-to: pi#set_ip
      summary: Set current PI ip.
      parameters:
      - in: body
        name: body
        required: 'true'
        schema:
          type: object
          required:
          - ip
          properties:
            ip:
              $ref: "#/definitions/ip"
      responses:
        '200':
          description: Set ip response
          schema:
            type: string
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
definitions:
  Error:
    type: object
    required:
    - errors
    properties:
      errors:
        type: array
        items:
          type: object
          required:
          - message
          - path
          properties:
            message:
              type: string
              description: Human readable error message
            path:
              type: string
              description: JSON pointer to the error
  ip:
    type: string
